# top right bottom left
window_padding_width 24 18 0 18

mouse_hide_wait 1.0

# 光标颜色使用当前文本颜色
cursor none
cursor_trail 1
cursor_trail_decay 0.1 0.4
# 当移动 1 个字符位置时也使用动效, 这样看着更平滑
cursor_trail_start_threshold 0

cursor_blink_interval 0.5 ease-in-out

# 用系统快捷键关闭窗口时不提示
confirm_os_window_close 0

# 开启动态 opacity
dynamic_background_opacity yes

close_on_child_death yes

# 从顶部左边开始分配多余空间,
# 避免从中间分配导致切分窗口时界面跳动
placement_strategy top-left

# 开启垂直方向分屏和全屏模式
enabled_layouts fat:bias=50,stack
