o# font family style
font_family		FiraCode Nerd Font Mono
bold_font		auto
italic_font		auto
bold_italic_font	auto

# font size
font_size	23.0

# specifically symbol map
# symbol_map U+e000-U+e00a,U+ea60-U+ebeb,U+e0a0-U+e0c8,U+e0ca,U+e0cc-U+e0d7,U+e200-U+e2a9,U+e300-U+e3e3,U+e5fa-U+e6b7,U+e700-U+e8ef,U+ed00-U+efc1,U+f000-U+f2ff,U+f000-U+f2e0,U+f300-U+f381,U+f400-U+f533,U+f0001-U+f1af0 MapleMono NF CN
# symbol_map U+4E00-U+9FA5,U+9FA6-U+9FCB LXGW WenKai

# the position of current cursor don't ligature
disable_ligatures	cursor

# 
modify_font underline_position 3
modify_font underline_thickness 50%
modify_font strikethrough_position 2px

modify_font cell_width +1px
modify_font cell_height +6px

text_composition_strategy 10 2
