# blackboard
foreground 		#979db4
background 		#202746

# the colors of the selection region by mouse
selection_foreground 	#000000
selection_background 	#ffffff

# Cursor colors
#cursor                  #f5e0dc
#cursor_text_color       #1e1e2e

cursor 			#979db4
cursor_text_color 	#202746

# URL underline color when hovering with mouse
url_color               #f5e0dc

# Kitty window border colors
active_border_color     #b4befe
inactive_border_color   #6c7086
bell_border_color       #f9e2af

# OS Window titlebar colors
wayland_titlebar_color 	system
macos_titlebar_color 	system

# Tab bar colors
active_tab_foreground   #11111b
active_tab_background   #cba6f7
inactive_tab_foreground #cdd6f4
inactive_tab_background #181825
tab_bar_background      #11111b

# Colors for marks (marked text in the terminal)
mark1_foreground #1e1e2e
mark1_background #b4befe
mark2_foreground #1e1e2e
mark2_background #cba6f7
mark3_foreground #1e1e2e
mark3_background #74c7ec

# The 16 terminal colors

## black
color0 #000000
color8 #000000

## red
color1 #de3d35
color9 #de3d35

## green
color2 #3e953a
color10 #3e953a

## yellow
color3 #d2b67b
color11 #d2b67b

## blue
color4 #2f5af3
color12 #2f5af3

## magenta
color5 #950095
color13 #a00095

## cyan
color6 #3e953a
color14 #3e953a

## white
color7 #bbbbbb
color15 #ffffff

## ENV
env Kitty_THEME=AtomOneLight
 
